# Generated by Django 6.0.1 on 2026-01-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='es_nuevo',
            field=models.BooleanField(default=True, verbose_name='¿Es Nuevo?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talles',
            field=models.CharField(blank=True, help_text='Ej: S, M, L', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.categoria'),
        ),
    ]
