# Generated by Django 6.0.1 on 2026-01-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_producto_es_nuevo_producto_talles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talles',
            field=models.CharField(blank=True, help_text='Ej: S, M, L o Único', max_length=100),
        ),
    ]
