# Generated by Django 6.0.1 on 2026-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria_slug_alter_producto_talles'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Anterior (Tachado)'),
        ),
    ]
