# Generated by Django 6.0.1 on 2026-01-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_precio_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Tu Estilo, Tu Aura', max_length=100)),
                ('subtitulo', models.CharField(blank=True, help_text='Ej: Colección Otoño/Invierno', max_length=200, null=True)),
                ('texto_boton', models.CharField(default='Ver Productos', max_length=50)),
                ('imagen', models.ImageField(help_text='Idealmente una imagen horizontal de alta calidad', upload_to='portadas/')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Portada',
                'verbose_name_plural': 'Configuración de Portada',
            },
        ),
    ]
